### ISSUE TITLE
Ética - Describir cómo el grupo se conforma como instrumento legal

### ISSUE THREAD

**Issue by Agustin197** [GRUPO-10-Organizador/PROYECTOFINAL#3]
(Empresa, Socios, CEO, Empleados) y si tendrán un contrato con que cláusulas.

**Comment by FranLombardi05** [comment]
Hola! Aca te envio un archivo sobre la "Conformacion como instrumento legal" sobre el proyecto.Porfa,si me recomiendan algo digan
[Proyecto_Final_ISPC.docx](https://github.com/user-attachments/files/15537292/Proyecto_Final_ISPC.docx)

**Comment by Facundo-kreff** [comment]
Buenas, acá mando algo que estube haciendo, no se si estara bien así, porfa diganme que cosas hay que corregir 
[Ética-Punto 2 al 6.docx](https://github.com/user-attachments/files/15597519/Etica-Punto.2.al.6.docx)

**Comment by Facundo-kreff** [comment]
Ahí mando un par de puntos mas 
[Ética-Punto 8 al 11.docx](https://github.com/user-attachments/files/15688391/Etica-Punto.8.al.11.docx)

**Comment by FranLombardi05** [comment]
Hola, buenas noches. Termine! Les adjunto el archivo. Junte toda la informacion y la ordene un poco
[Etica_Proyectofinal.docx](https://github.com/user-attachments/files/15688700/Etica_Proyectofinal.docx)
